importing libraries

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report,mean_squared_error

In [ ]:
data= pd.read_csv('e-shop clothing 2008.csv')
data.columns=['year','month','day','order','country','session_ID','page_1','colour','location','model photography','price','price_2','page']
print('No.of instances=%d' %(data.shape[0]))
print('No.of attributes=%d' %(data.shape[1]))
data.head()

No.of instances=1000
No.of attributes=13


year  month  day  order  ...  model photography  price  price_2  page
0  2008      4    1      1  ...                  1     28        2     1
1  2008      4    1      2  ...                  1     33        2     1
2  2008      4    1      3  ...                  1     52        1     1
3  2008      4    1      4  ...                  2     38        2     1
4  2008      4    1      5  ...                  2     52        1     1

[5 rows x 13 columns]

In [ ]:
print(data.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               1000 non-null   int64
 1   month              1000 non-null   int64
 2   day                1000 non-null   int64
 3   order              1000 non-null   int64
 4   country            1000 non-null   int64
 5   session_ID         1000 non-null   int64
 6   page_1             1000 non-null   int64
 7   colour             1000 non-null   int64
 8   location           1000 non-null   int64
 9   model photography  1000 non-null   int64
 10  price              1000 non-null   int64
 11  price_2            1000 non-null   int64
 12  page               1000 non-null   int64
dtypes: int64(13)
memory usage: 101.7 KB
None


Splitting the dataset into train and test sets

In [ ]:
x = data.iloc[:,1:12].values
y = data.iloc[:, -1].values
y=y.reshape(-1,1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state =0)

# Classification Analysis:

# 1) Random forest

In [ ]:
model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=1)
model.fit(x_train, y_train)
accuracy=model.score(x_test, y_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [ ]:
print('The accuracy of the model is ',accuracy)
print('\nConfusion matrix:\n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy of the model is  0.84

Confusion matrix:
 [[151   4   1   0   0]
 [ 34  14   2   0   0]
 [ 18   0   5   1   0]
 [ 11   4   0   1   0]
 [  4   0   0   0   0]]
              precision    recall  f1-score   support

           1       0.69      0.97      0.81       156
           2       0.64      0.28      0.39        50
           3       0.62      0.21      0.31        24
           4       0.50      0.06      0.11        16
           5       0.00      0.00      0.00         4

    accuracy                           0.68       250
   macro avg       0.49      0.30      0.32       250
weighted avg       0.65      0.68      0.62       250



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 2)Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 500000)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = model.score(x_test, y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print('The accuracy of the model is ',accuracy)
print('\nConfusion matrix:\n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy of the model is  0.66

Confusion matrix:
 [[147   8   1   0   0]
 [ 40   9   1   0   0]
 [ 16   1   5   2   0]
 [ 11   1   0   4   0]
 [  4   0   0   0   0]]
              precision    recall  f1-score   support

           1       0.67      0.94      0.79       156
           2       0.47      0.18      0.26        50
           3       0.71      0.21      0.32        24
           4       0.67      0.25      0.36        16
           5       0.00      0.00      0.00         4

    accuracy                           0.66       250
   macro avg       0.51      0.32      0.35       250
weighted avg       0.63      0.66      0.60       250



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 3)K-Nearest Neighbour

In [ ]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
acc=accuracy_score(y_test, y_pred)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """


In [ ]:
print(acc)
print('\nConfusion matrix:\n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.708

Confusion matrix:
 [[146   9   1   0   0]
 [ 24  25   1   0   0]
 [ 15   6   3   0   0]
 [ 11   2   0   3   0]
 [  4   0   0   0   0]]
              precision    recall  f1-score   support

           1       0.73      0.94      0.82       156
           2       0.60      0.50      0.54        50
           3       0.60      0.12      0.21        24
           4       1.00      0.19      0.32        16
           5       0.00      0.00      0.00         4

    accuracy                           0.71       250
   macro avg       0.59      0.35      0.38       250
weighted avg       0.70      0.71      0.66       250



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 4)Support vector machine (SVC) with Radial Basis function

In [ ]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
accuracy = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)

In [ ]:
print('The accuracy of the model is ',accuracy.mean())
print('\nConfusion matrix:\n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy of the model is  0.6946666666666668

Confusion matrix:
 [[154   1   1   0   0]
 [ 36  12   2   0   0]
 [ 17   1   6   0   0]
 [ 14   0   1   1   0]
 [  4   0   0   0   0]]
              precision    recall  f1-score   support

           1       0.68      0.99      0.81       156
           2       0.86      0.24      0.38        50
           3       0.60      0.25      0.35        24
           4       1.00      0.06      0.12        16
           5       0.00      0.00      0.00         4

    accuracy                           0.69       250
   macro avg       0.63      0.31      0.33       250
weighted avg       0.72      0.69      0.62       250



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 5)Support vector machine (SVC) with Polynomial function

In [ ]:
 classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
accuracy = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)

In [ ]:
print('The accuracy of the model is ',accuracy.mean())
print('\nConfusion matrix:\n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy of the model is  0.6986666666666668

Confusion matrix:
 [[151   4   1   0   0]
 [ 34  14   2   0   0]
 [ 18   0   5   1   0]
 [ 11   4   0   1   0]
 [  4   0   0   0   0]]
              precision    recall  f1-score   support

           1       0.69      0.97      0.81       156
           2       0.64      0.28      0.39        50
           3       0.62      0.21      0.31        24
           4       0.50      0.06      0.11        16
           5       0.00      0.00      0.00         4

    accuracy                           0.68       250
   macro avg       0.49      0.30      0.32       250
weighted avg       0.65      0.68      0.62       250



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
